Make _release and _withdraw virtual
Uniswap/the-compact pull request #34
Opened 2024-12-12 05:29 UTC by zeroknots

I'm planning to inherit the-compact's claim / digest logic but have customized logic for `_release() `and `_withdraw()`. Having these virtual would be of great help. So I can use the-compact as a dependency

2024-12-16 18:07 UTC, 0age commented
looks like solady / soledge got committed (they should still be a library) otherwise SGTM

2024-12-16 18:07 UTC, 0age requested changes
are the submodule changes here just a newer version of Solady?

2024-12-17 01:48 UTC, zeroknots commented
@0age indeed that was the case. cleaned up the PR to only include the virtual function. apologies

2025-01-06 02:42 UTC, zeroknots commented
bumping this. @0age  do you think we can get this merged?

2025-01-17 11:50 UTC, merged